from .auto_select_bot import enable_auto_select_bot, register_list_targets
from .const import SupportedAdapters, SupportedPlatform, supported_adapter_names
from .exceptions import AdapterNotInstalled, AdapterNotSupported
from .helpers import extract_adapter_type
from .platform_send_target import (
    AllSupportedPlatformTarget,
    PlatformTarget,
    TargetKaiheilaChannel,
    TargetKaiheilaPrivate,
    TargetOB12Unknow,
    TargetQQGroup,
    TargetQQGuildChannel,
    TargetQQGuildDirect,
    TargetQQPrivate,
    TargetTelegramCommon,
    TargetTelegramForum,
    extract_target,
    get_target,
    register_convert_to_arg,
    register_sender,
    register_target_extractor,
)
from .types import (
    AggregatedMessageFactory,
    BuildFunc,
    CustomBuildFunc,
    MessageFactory,
    MessageSegmentFactory,
    assamble_message_factory,
    do_build,
    do_build_custom,
    register_ms_adapter,
)

__all__ = [
    "SupportedAdapters",
    "SupportedPlatform",
    "supported_adapter_names",
    "AdapterNotInstalled",
    "AdapterNotSupported",
    "MessageSegmentFactory",
    "MessageFactory",
    "AggregatedMessageFactory",
    "register_ms_adapter",
    "extract_adapter_type",
    "BuildFunc",
    "CustomBuildFunc",
    "do_build",
    "do_build_custom",
    "extract_target",
    "get_target",
    "register_target_extractor",
    "register_sender",
    "assamble_message_factory",
    "register_convert_to_arg",
    "register_target_extractor",
    "PlatformTarget",
    "TargetQQGroup",
    "TargetQQPrivate",
    "TargetQQGuildChannel",
    "TargetQQGuildDirect",
    "TargetKaiheilaChannel",
    "TargetKaiheilaPrivate",
    "TargetOB12Unknow",
    "TargetTelegramCommon",
    "TargetTelegramForum",
    "AllSupportedPlatformTarget",
    "auto_select_bot",
    "register_list_targets",
    "enable_auto_select_bot",
]
